services:
  postgres:
    image: 'postgres:16'
    environment:
      - 'POSTGRES_DB=recipes'
      - 'POSTGRES_PASSWORD=secretsauce'
      - 'POSTGRES_USER=chef'
    ports:
      - '5432'
    network_mode: host
  appwrite:
    image: 'appwrite/appwrite:1.5'
    ports:
      - '8080:80'
    network_mode: host
